services: 
  phpaladin-probot:
    image: phpaladin:development
    container_name: phpaladin-probot-dev
    build:
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "${PWD}/private-key.pem:/app/private-key.pem"
  docker-in-docker:
    container_name: docker-in-docker
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    expose:
      - 2375
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375"]