networks:
  internal:
services: 
  phpaladin-probot:
    networks:
      - internal
    container_name: phpaladin-probot
    build:
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "${PWD}/private-key.pem:/usr/src/app/private-key.pem"
    depends_on:
      - docker-in-docker
  docker-in-docker:
    networks:
      - internal
    container_name: docker-in-docker
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    expose:
      - 2375
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375"]