networks:
  internal:
services: 
  phpaladin-probot:
    networks:
      - internal
    image: phpaladin:development
    container_name: phpaladin-probot-dev
    build:
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "${PWD}/private-key.pem:/app/private-key.pem"
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        target: /app/node_modules
        source: ./node_modules
    depends_on:
      - docker-in-docker
  docker-in-docker:
    networks:
      - internal
    container_name: docker-in-docker
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    expose:
      - 2375
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375"]